name: Fetch Google Sheets Data

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sunday at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-sheet-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch Google Sheets Data
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Use curl to fetch data from Google Sheets
          curl "https://sheets.googleapis.com/v4/spreadsheets/1KdnH8YliEMnmQbGetB8b1zcQwlKg6zp-YwMW5ALCQOs/values/Sheet1!A2:F?key=${API_KEY}" -o sheetData.json
          
          # Commit and push data to the repository
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add sheetData.json
          git commit -m "Update sheet data"
          git push
